### ISSUE TITLE
in "channel_rename" message: "when expecting a Time, encountered String instead"

### ISSUE THREAD

**Issue by peddie** [mpickering/slack-api#34]
{"type":"channel_rename","channel":{"id":"<elided>","is_channel":true,"name":"deployer","created":"1439493050"},"event_ts":"1440525698.753638"}
    when expecting a Time, encountered String instead

**Comment by mpickering** [comment]
This is to do with the `created` field I think?

**Comment by jsteiner** [comment]
Yes, it does seem to be because of `created`. What would be the preferred solution for this? I saw your issue [here](https://github.com/slackhq/slack-api-docs/issues/7) regarding the timestamp inconsistencies. It seems though that there are more inconsistencies than listed in that issue, as even the `created`/`edited`/`timestamp` variety can either be integers or strings. e.g. `channel_rename` uses a String for `created`, but most other things are using integers.

Would you be opposed to reading it in as `Text` for now?
