### ISSUE TITLE
How to PM a user

### ISSUE THREAD

**Issue by apolishch** [mpickering/slack-api#69]
Given a user from https://hackage.haskell.org/package/slack-api-0.9/docs/Web-Slack-Types-Session.html#t:SlackSession, or even better based on the UserId in the Message event, how would I go about issuing a DM from the bot to that user?

I'm having a little bit of trouble finding this anywhere in the documentaiton.

Thanks!
Abe

**Comment by mpickering** [comment]
The documentation says:

> You can send a message to a private group or direct message channel in the same way, but using a Group ID (C024BE91L) or DM channel ID (D024BE91L).

So I guess a private message is a dm channel?

**Comment by apolishch** [comment]
derp. Thank you

**Comment by asayers** [comment]
Abe,

A few things to note. First of all, as @mpickering says, you can send messages to either group channels (represented by a `ChannelId`) or to DM channels (represented by an `IMId`). Therefore, the type of `sendMessage` *should* be:

```haskell
sendMessage :: Either IMId ChannelId -> T.Text -> Slack s ()
```

...but in fact it's:

```haskell
sendMessage :: ChannelId -> T.Text -> Slack s ()
```

We should probably change this. Until then, you can use `Web.Slack.Types.IM.imToChannel :: IMId -> ChannelId`, which looks a bit more legit than using `coerce`.

Now, you have a `UserId` and you want to get your hands on the relevant `IMId`. Unfortunately, Slack makes this a bit more complicated than you'd think. You might assume that you'd automatically get a DM channel for each user, but this isn't the case. You have to explicitly establish a DM channel with a particular user. Normally this happens when one user DMs another for the first time.

If the user you're looking for has already DM'd your slackbot, then you're in luck. The `SlackSession` contains a list of `IM`s - one item for each DM channel which has been established with your slackbot's user. These `IM` items contain a `UserId` and an `IMId`, so you just need to do a lookup:

```haskell
lookupIMId :: SlackSession -> UserId -> Maybe IMId
lookupIMId session uid :: session ^? slackIMs . imUser . only uid
```

However, if a DM channel hasn't yet been established yet with the user you're looking for, then you won't find them in `slackIMs`. In this case, you need to either call the [`im.open`](https://api.slack.com/methods/im.open) web API method, or convince the user to talk to your bot.
